#!/usr/bin/env bash
# MES X-Ray — one-click start / stop / restart for local development and demos.
#
#   scripts/xray.sh start            build + start API (:5080) and Web UI (:5173) in the background
#   scripts/xray.sh stop             stop what this script started
#   scripts/xray.sh restart          stop, rebuild, start
#   scripts/xray.sh status           processes, ports, API health
#   scripts/xray.sh logs             follow API + Web logs (Ctrl-C to quit)
#
# Everything generated by this script (pid files, logs) lives under artifacts/run (git-ignored).
# The script never touches a database or an AI provider: the API runs offline from fixtures/.
# Requires bash 3.2+ (macOS default), dotnet SDK (see global.json), Node.js 20+, curl, lsof.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RUN_DIR="$ROOT/artifacts/run"
LOG_DIR="$RUN_DIR/logs"
API_PROJECT="$ROOT/src/MesXray.Api"
WEB_PROJECT="$ROOT/src/MesXray.Web"

API_PORT="${XRAY_API_PORT:-5080}"
WEB_PORT="${XRAY_WEB_PORT:-5173}"
API_URL="http://localhost:$API_PORT"
WEB_URL="http://localhost:$WEB_PORT"
HEALTH_URL="$API_URL/api/xray/health"
DEMO_URL="$WEB_URL/?order=PICK0843858&field=availableQuantity&scope=T12288&investigate=1"

CONFIG="Debug"
NO_BUILD=0
FORCE=0
OPEN_BROWSER=0
TARGET="all"   # all | api | web

# ---------------------------------------------------------------- output helpers
if [[ -t 1 ]]; then
  C_RESET=$'\033[0m'; C_DIM=$'\033[2m'; C_GREEN=$'\033[32m'; C_YELLOW=$'\033[33m'; C_RED=$'\033[31m'; C_BOLD=$'\033[1m'
else
  C_RESET=""; C_DIM=""; C_GREEN=""; C_YELLOW=""; C_RED=""; C_BOLD=""
fi
log()  { printf '%s▸ %s%s\n' "$C_BOLD" "$*" "$C_RESET"; }
ok()   { printf '%s✔ %s%s\n' "$C_GREEN" "$*" "$C_RESET"; }
warn() { printf '%s! %s%s\n' "$C_YELLOW" "$*" "$C_RESET" >&2; }
die()  { printf '%s✘ %s%s\n' "$C_RED" "$*" "$C_RESET" >&2; exit 1; }

usage() {
  sed -n '2,12p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
  cat <<EOF

Options:
  --api-only        only the API              --web-only   only the Web UI
  --release         build/run the API in Release configuration (default: Debug)
  --no-build        start: skip 'dotnet build' and run the last build output
  --open            start/restart: open the demo scene in the browser when ready
  --force           stop: also kill any other process listening on the API/Web ports

Environment:
  XRAY_API_PORT=$API_PORT  XRAY_WEB_PORT=$WEB_PORT  ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
  A repo-root .env (see .env.example) is loaded automatically; MESXRAY_AI_API_KEY etc. pass through.
EOF
}

# ---------------------------------------------------------------- generic helpers
require_cmd() { command -v "$1" >/dev/null 2>&1 || die "'$1' is required but not found on PATH."; }

# Load KEY=VALUE lines from a repo-root .env without executing anything else in it.
load_dotenv() {
  local file="$ROOT/.env" line key
  [[ -f "$file" ]] || return 0
  while IFS= read -r line || [[ -n "$line" ]]; do
    [[ "$line" =~ ^[[:space:]]*# || -z "${line//[[:space:]]/}" ]] && continue
    key="${line%%=*}"
    [[ "$key" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || continue
    export "$key=${line#*=}"
  done < "$file"
  log "Loaded environment from .env"
}

pid_file() { printf '%s/%s.pid\n' "$RUN_DIR" "$1"; }

# Prints the pid of a service if it is alive; removes stale pid files.
running_pid() {
  local file pid
  file="$(pid_file "$1")"
  [[ -f "$file" ]] || return 1
  pid="$(cat "$file" 2>/dev/null || true)"
  if [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null; then
    printf '%s\n' "$pid"
    return 0
  fi
  rm -f "$file"
  return 1
}

port_listeners() { lsof -nP -iTCP:"$1" -sTCP:LISTEN -t 2>/dev/null || true; }

describe_pid() { ps -o pid=,command= -p "$1" 2>/dev/null | sed 's/^ *//' || true; }

# wait_for_http <url> <seconds> <label> [<pid>] — succeeds when the URL answers 2xx/3xx.
wait_for_http() {
  local url="$1" timeout="$2" label="$3" pid="${4:-}" waited=0
  while (( waited < timeout * 2 )); do
    if curl -fsS -o /dev/null --max-time 2 "$url" 2>/dev/null; then
      return 0
    fi
    if [[ -n "$pid" ]] && ! kill -0 "$pid" 2>/dev/null; then
      warn "$label exited before it became ready."
      return 1
    fi
    sleep 0.5
    waited=$((waited + 1))
  done
  warn "$label did not answer at $url within ${timeout}s."
  return 1
}

# stop_pid <pid> <label> — TERM the process and its children, escalate to KILL after 10s.
stop_pid() {
  local pid="$1" label="$2" waited=0
  log "Stopping $label (pid $pid)…"
  pkill -TERM -P "$pid" 2>/dev/null || true
  kill -TERM "$pid" 2>/dev/null || true
  while kill -0 "$pid" 2>/dev/null && (( waited < 20 )); do
    sleep 0.5
    waited=$((waited + 1))
  done
  if kill -0 "$pid" 2>/dev/null; then
    warn "$label did not exit gracefully; sending SIGKILL."
    pkill -KILL -P "$pid" 2>/dev/null || true
    kill -KILL "$pid" 2>/dev/null || true
  fi
}

want_api() { [[ "$TARGET" == "all" || "$TARGET" == "api" ]]; }
want_web() { [[ "$TARGET" == "all" || "$TARGET" == "web" ]]; }

# ---------------------------------------------------------------- API
build_api() {
  log "Building MesXray.Api ($CONFIG)…"
  if ! dotnet build "$API_PROJECT/MesXray.Api.csproj" -c "$CONFIG" -nologo -v q > "$LOG_DIR/api-build.log" 2>&1; then
    cat "$LOG_DIR/api-build.log" >&2
    die "dotnet build failed (see artifacts/run/logs/api-build.log)."
  fi
}

start_api() {
  local pid dll config_dir listeners
  if pid="$(running_pid api)"; then
    ok "API already running (pid $pid) at $API_URL"
    return 0
  fi
  listeners="$(port_listeners "$API_PORT")"
  if [[ -n "$listeners" ]]; then
    for pid in $listeners; do warn "Port $API_PORT is in use: $(describe_pid "$pid")"; done
    die "Free port $API_PORT ('scripts/xray.sh stop --force') or set XRAY_API_PORT."
  fi

  (( NO_BUILD )) || build_api
  config_dir="$(printf '%s' "$CONFIG" | tr '[:upper:]' '[:lower:]')"
  dll="$ROOT/artifacts/bin/MesXray.Api/$config_dir/MesXray.Api.dll"
  [[ -f "$dll" ]] || die "Build output not found: $dll (run without --no-build)."

  log "Starting API ($CONFIG) at $API_URL…"
  # Run the built DLL directly (not 'dotnet run') so there is exactly one process to manage.
  # Working directory = project folder: that is the content root (appsettings.json, wwwroot) and the
  # fixture folder is resolved by walking up from there (XRay:Fixtures:Root).
  (
    cd "$API_PROJECT"
    export ASPNETCORE_ENVIRONMENT="${ASPNETCORE_ENVIRONMENT:-Development}"
    export Kestrel__Endpoints__Http__Url="$API_URL"
    nohup dotnet "$dll" > "$LOG_DIR/api.log" 2>&1 &
    echo $! > "$(pid_file api)"
  )
  pid="$(cat "$(pid_file api)")"
  if wait_for_http "$HEALTH_URL" 90 "API" "$pid"; then
    ok "API ready (pid $pid) — $API_URL  · OpenAPI: $API_URL/openapi/v1.json"
  else
    tail -n 40 "$LOG_DIR/api.log" >&2 || true
    die "API failed to start (log: artifacts/run/logs/api.log)."
  fi
}

# ---------------------------------------------------------------- Web
start_web() {
  local pid listeners
  if pid="$(running_pid web)"; then
    ok "Web already running (pid $pid) at $WEB_URL"
    return 0
  fi
  listeners="$(port_listeners "$WEB_PORT")"
  if [[ -n "$listeners" ]]; then
    for pid in $listeners; do warn "Port $WEB_PORT is in use: $(describe_pid "$pid")"; done
    die "Free port $WEB_PORT ('scripts/xray.sh stop --force') or set XRAY_WEB_PORT."
  fi

  if [[ ! -d "$WEB_PROJECT/node_modules" ]]; then
    log "Installing npm packages (first run)…"
    if ! (cd "$WEB_PROJECT" && npm ci --no-audit --no-fund > "$LOG_DIR/web-install.log" 2>&1); then
      cat "$LOG_DIR/web-install.log" >&2
      die "npm ci failed (see artifacts/run/logs/web-install.log)."
    fi
  fi

  log "Starting Web UI (Vite dev server, /api → $API_URL) at $WEB_URL…"
  # Invoke vite.js with node directly (not 'npm run dev') so the pid we record is the server itself.
  (
    cd "$WEB_PROJECT"
    export VITE_XRAY_API_URL="$API_URL"
    nohup node node_modules/vite/bin/vite.js --port "$WEB_PORT" --strictPort > "$LOG_DIR/web.log" 2>&1 &
    echo $! > "$(pid_file web)"
  )
  pid="$(cat "$(pid_file web)")"
  if wait_for_http "$WEB_URL/" 60 "Web" "$pid"; then
    ok "Web ready (pid $pid) — $WEB_URL"
  else
    tail -n 40 "$LOG_DIR/web.log" >&2 || true
    die "Web UI failed to start (log: artifacts/run/logs/web.log)."
  fi
}

# ---------------------------------------------------------------- commands
cmd_start() {
  mkdir -p "$LOG_DIR"
  require_cmd curl; require_cmd lsof
  if want_api; then require_cmd dotnet; fi
  if want_web; then require_cmd node; require_cmd npm; fi
  load_dotenv

  if want_api; then start_api; fi
  if want_web; then start_web; fi

  printf '\n'
  if want_web; then
    printf '  UI    %s\n' "$WEB_URL"
    printf '  Demo  %s\n' "$DEMO_URL"
  fi
  if want_api; then printf '  API   %s\n' "$HEALTH_URL"; fi
  printf '  Logs  scripts/xray.sh logs\n\n'

  if (( OPEN_BROWSER )) && want_web; then
    if command -v open >/dev/null 2>&1; then open "$DEMO_URL"
    elif command -v xdg-open >/dev/null 2>&1; then xdg-open "$DEMO_URL" >/dev/null 2>&1 &
    else warn "No 'open'/'xdg-open' found; open $DEMO_URL manually."
    fi
  fi
}

stop_service() {
  local name="$1" label="$2" port="$3" pid listeners
  if pid="$(running_pid "$name")"; then
    stop_pid "$pid" "$label"
    rm -f "$(pid_file "$name")"
    ok "$label stopped."
  else
    printf '%s  %s is not running (no pid recorded).%s\n' "$C_DIM" "$label" "$C_RESET"
  fi

  listeners="$(port_listeners "$port")"
  if [[ -z "$listeners" ]]; then return 0; fi
  if (( FORCE )); then
    for pid in $listeners; do
      warn "--force: killing pid $pid on port $port: $(describe_pid "$pid")"
      stop_pid "$pid" "port $port listener"
    done
  else
    for pid in $listeners; do
      warn "Port $port is still held by pid $pid ($(describe_pid "$pid")) — not started by this script. Use 'stop --force' to kill it."
    done
  fi
}

cmd_stop() {
  require_cmd lsof
  mkdir -p "$RUN_DIR"
  if want_web; then stop_service web "Web UI" "$WEB_PORT"; fi
  if want_api; then stop_service api "API" "$API_PORT"; fi
}

cmd_status() {
  require_cmd lsof
  local pid listeners health
  printf '%-6s %-9s %-10s %s\n' "SVC" "PID" "STATE" "URL"
  if want_api; then
    if pid="$(running_pid api)"; then
      if health="$(curl -fsS --max-time 3 "$HEALTH_URL" 2>/dev/null)"; then
        printf '%-6s %-9s %s%-10s%s %s  %s\n' "api" "$pid" "$C_GREEN" "healthy" "$C_RESET" "$API_URL" "$(printf '%s' "$health" | head -c 96)…"
      else
        printf '%-6s %-9s %s%-10s%s %s\n' "api" "$pid" "$C_YELLOW" "starting?" "$C_RESET" "$API_URL"
      fi
    else
      listeners="$(port_listeners "$API_PORT")"
      if [[ -n "$listeners" ]]; then
        printf '%-6s %-9s %s%-10s%s %s  (port held by another process)\n' "api" "$listeners" "$C_YELLOW" "foreign" "$C_RESET" "$API_URL"
      else
        printf '%-6s %-9s %s%-10s%s %s\n' "api" "-" "$C_DIM" "stopped" "$C_RESET" "$API_URL"
      fi
    fi
  fi
  if want_web; then
    if pid="$(running_pid web)"; then
      if curl -fsS -o /dev/null --max-time 3 "$WEB_URL/" 2>/dev/null; then
        printf '%-6s %-9s %s%-10s%s %s\n' "web" "$pid" "$C_GREEN" "healthy" "$C_RESET" "$WEB_URL"
      else
        printf '%-6s %-9s %s%-10s%s %s\n' "web" "$pid" "$C_YELLOW" "starting?" "$C_RESET" "$WEB_URL"
      fi
    else
      listeners="$(port_listeners "$WEB_PORT")"
      if [[ -n "$listeners" ]]; then
        printf '%-6s %-9s %s%-10s%s %s  (port held by another process)\n' "web" "$listeners" "$C_YELLOW" "foreign" "$C_RESET" "$WEB_URL"
      else
        printf '%-6s %-9s %s%-10s%s %s\n' "web" "-" "$C_DIM" "stopped" "$C_RESET" "$WEB_URL"
      fi
    fi
  fi
  printf '%slogs: %s%s\n' "$C_DIM" "$LOG_DIR" "$C_RESET"
}

cmd_logs() {
  local files=()
  if want_api && [[ -f "$LOG_DIR/api.log" ]]; then files+=("$LOG_DIR/api.log"); fi
  if want_web && [[ -f "$LOG_DIR/web.log" ]]; then files+=("$LOG_DIR/web.log"); fi
  if (( ${#files[@]} == 0 )); then die "No logs yet under artifacts/run/logs — start the services first."; fi
  exec tail -n 50 -F "${files[@]}"
}

# ---------------------------------------------------------------- main
COMMAND="${1:-}"
if [[ -n "$COMMAND" ]]; then shift; fi
for arg in "$@"; do
  case "$arg" in
    --api-only) TARGET="api" ;;
    --web-only) TARGET="web" ;;
    --release)  CONFIG="Release" ;;
    --no-build) NO_BUILD=1 ;;
    --force)    FORCE=1 ;;
    --open)     OPEN_BROWSER=1 ;;
    -h|--help)  usage; exit 0 ;;
    *) usage >&2; die "Unknown option: $arg" ;;
  esac
done

case "$COMMAND" in
  start)   cmd_start ;;
  stop)    cmd_stop ;;
  restart) cmd_stop; printf '\n'; cmd_start ;;
  status)  cmd_status ;;
  logs)    cmd_logs ;;
  -h|--help|help|"") usage; [[ -n "$COMMAND" ]] || exit 1 ;;
  *) usage >&2; die "Unknown command: $COMMAND" ;;
esac
